<?php
global $SESSION, $USER_TYPES;

$STAFF = array(
    [
        "text" => "Home",
        "path" => '/',
        "icon" => UseIcon('home', 'feather')
    ],
    [
        "text" => "Patients",
        "path" => '/patients',
        "icon" => UseIcon('user', 'feather'),
        "sub-content" => [
            [
                "text" => "Search Patients",
                "path" => '/patients/search_patients',
                "icon" => UseIcon('search', 'feather')
            ],
            [
                "text" => "Evaluations",
                "path" => '/patients/evaluations',
                "icon" => UseIcon('clipboard', 'feather')
            ],
            [
                "text" => "Color Vision Eval",
                "path" => '/patients/color_vision_evaluations',
                "icon" => '<i data-feather="eye"></i>'
            ],
            [
                "text" => "Dry Eyes Eval",
                "path" => '/patients/dry_eyes_evaluations',
                "icon" => UseIcon('droplet', 'feather')
            ],
        ]
    ],
    [
        "text" => "Point of Sales",
        "path" => '/pos',
        "icon" => UseIcon('dollar-sign', 'feather'),
        "sub-content" => [
            [
                "text" => "Point of Sales",
                "path" => '/pos/point_of_sales',
                "icon" => UseIcon('credit-card', 'feather')
            ],
            [
                "text" => "Orders",
                "path" => '/pos/orders',
                "icon" => UseIcon('shopping-cart', 'feather')
            ],
            [
                "text" => "Lab Orders",
                "path" => '/pos/lab_orders',
                "icon" => UseIcon('flask', 'feather')
            ],
            [
                "text" => "Delivery",
                "path" => '/pos/order_delivery',
                "icon" => UseIcon('truck', 'feather')
            ],
            [
                "text" => "Payments",
                "path" => '/pos/payments',
                "icon" => UseIcon('credit-card', 'feather')
            ],
        ]
    ],
    [
        "text" => "Inventory",
        "path" => '/inventory',
        "icon" => UseIcon('package', 'feather'),
        "sub-content" => [
            [
                "text" => "Products",
                "path" => '/inventory/products',
                "icon" => UseIcon('box', 'feather')
            ],
            [
                "text" => "Packages",
                "path" => '/inventory/packages',
                "icon" => UseIcon('package', 'feather')
            ],
            [
                "text" => "Product Types",
                "path" => '/inventory/product_types',
                "icon" => UseIcon('tag', 'feather')
            ],
            [
                "text" => "Suppliers",
                "path" => '/inventory/suppliers',
                "icon" => UseIcon('truck', 'feather')
            ],
            [
                "text" => "Categories",
                "path" => '/inventory/categories',
                "icon" => UseIcon('folder', 'feather')
            ],
        ]
    ],
    [
        "text" => "Schedule",
        "path" => '/services/schedule',
        "icon" => UseIcon('calendar', 'feather')
    ],
);

$ADMIN = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => UseIcon('activity', 'feather')
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => UseIcon('rss', 'feather')
    ],
    [
        "text" => "Students",
        "path" => '/students',
        "icon" => UseIcon('users', 'feather'),
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/students/students',
                "icon" => UseIcon('users', 'feather')
            ],
            [
                "text" => "Import Students",
                "path" => '/students/import_students',
                "icon" => UseIcon('upload', 'feather')
            ],
            [
                "text" => "Search Students",
                "path" => '/students/search_students',
                "icon" => UseIcon('search', 'feather')
            ],
        ]
    ],
    [
        "text" => "Faculty Management",
        "path" => '/faculty',
        "icon" => UseIcon('briefcase', 'feather'),
        "sub-content" => [
            [
                "text" => "Professors",
                "path" => '/faculty/professors',
                "icon" => UseIcon('user-check', 'feather')
            ],
        ]
    ],
    [
        "text" => "Maintenance",
        "path" => '/maintenance',
        "icon" => UseIcon('tool', 'feather'),
        "sub-content" => [
            [
                "text" => "Sections",
                "path" => '/maintenance/sections',
                "icon" => UseIcon('grid', 'feather')
            ],
            [
                "text" => "Courses",
                "path" => '/maintenance/courses',
                "icon" => UseIcon('book-open', 'feather')
            ],
            [
                "text" => "Subjects",
                "path" => '/maintenance/subjects',
                "icon" => UseIcon('book', 'feather')
            ],
            [
                "text" => "Classrooms",
                "path" => '/maintenance/classrooms',
                "icon" => UseIcon('layout', 'feather')
            ],
            [
                "text" => "Departments",
                "path" => '/maintenance/departments',
                "icon" => UseIcon('briefcase', 'feather')
            ],
            [
                "text" => "Events",
                "path" => '/maintenance/events',
                "icon" => UseIcon('calendar', 'feather')
            ],
        ]
    ],
);

$STUDENT = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => UseIcon('activity', 'feather')
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => UseIcon('rss', 'feather'),
        "sub-content" => [
            [
                "text" => "Public",
                "path" => '/newsfeed',
                "icon" => UseIcon('rss', 'feather'),
            ],
            [
                "text" => "Subjects",
                "path" => '/newsfeed_subjects',
                "icon" => UseIcon('rss', 'feather'),
                "sub-content" => [
                    [
                        "text" => "Public",
                        "path" => '/newsfeed/public',
                        "icon" => UseIcon('rss', 'feather'),
                    ],
                ]
            ],
        ]
    ],
    [
        "text" => "My Classes",
        "path" => '/me/classes',
        "icon" => UseIcon('book', 'feather')
    ],
);

$isProfessor = $SESSION->user_type == 2 && !empty($SESSION->getAsProfessor());

$FACULTY = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => UseIcon('activity', 'feather')
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => UseIcon('rss', 'feather'),
        "sub-content" => [
            [
                "text" => "Public",
                "path" => '/newsfeed',
                "icon" => UseIcon('rss', 'feather'),
            ],
            ($isProfessor ? [
                "text" => "Subjects",
                "path" => '/newsfeed_subjects',
                "icon" => UseIcon('rss', 'feather'),
                "sub-content" => [
                    [
                        "text" => "Public",
                        "path" => '/newsfeed/public',
                        "icon" => UseIcon('rss', 'feather'),
                    ],
                ]
            ] : [])
        ],
    ],
    ($isProfessor ? [
        "text" => "My Classes",
        "path" => '/me/classes',
        "icon" => UseIcon('layout', 'feather')
    ] : []),
    ($isProfessor ? [
        "text" => "My Resources",
        "path" => '/me/resources',
        "icon" => UseIcon('folder', 'feather')
    ] : []),
);

$SUPERADMIN = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => UseIcon('activity', 'feather')
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => UseIcon('rss', 'feather')
    ],
    [
        "text" => "Students",
        "path" => '/students',
        "icon" => UseIcon('users', 'feather'),
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/students/students',
                "icon" => UseIcon('users', 'feather')
            ],
            [
                "text" => "Import Students",
                "path" => '/students/import_students',
                "icon" => UseIcon('upload', 'feather')
            ],
            [
                "text" => "Search Students",
                "path" => '/students/search_students',
                "icon" => UseIcon('search', 'feather')
            ],
        ]
    ],
    [
        "text" => "Faculty Management",
        "path" => '/faculty',
        "icon" => UseIcon('briefcase', 'feather'),
        "sub-content" => [
            [
                "text" => "Professors",
                "path" => '/faculty/professors',
                "icon" => UseIcon('user-check', 'feather')
            ],
        ]
    ],
    [
        "text" => "Maintenance",
        "path" => '/maintenance',
        "icon" => '<i data-feather="tool"></i>',
        "sub-content" => [
            [
                "text" => "Sections",
                "path" => '/maintenance/sections',
                "icon" => UseIcon('grid', 'feather')
            ],
            [
                "text" => "Courses",
                "path" => '/maintenance/courses',
                "icon" => UseIcon('book-open', 'feather')
            ],
            [
                "text" => "Subjects",
                "path" => '/maintenance/subjects',
                "icon" => UseIcon('book', 'feather')
            ],
            [
                "text" => "Classrooms",
                "path" => '/maintenance/classrooms',
                "icon" => UseIcon('layout', 'feather')
            ],
            [
                "text" => "Departments",
                "path" => '/maintenance/departments',
                "icon" => UseIcon('briefcase', 'feather')
            ],
            [
                "text" => "Events",
                "path" => '/maintenance/events',
                "icon" => UseIcon('calendar', 'feather')
            ],
            [
                "text" => "Database Management",
                "path" => '/maintenance/database_management',
                "icon" => UseIcon('database', 'feather')
            ],
        ]
    ],
    [
        "text" => "Accounts",
        "path" => '/accounts',
        "icon" => UseIcon('users', 'feather'),
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/accounts/students',
                "icon" => UseIcon('user', 'feather')
            ],
            [
                "text" => "Faculty Members",
                "path" => '/accounts/faculty_members',
                "icon" => UseIcon('user-check', 'feather')
            ],
            [
                "text" => "Administrators",
                "path" => '/accounts/administrators',
                "icon" => UseIcon('user-plus', 'feather')
            ],
        ]
    ],
);

$ALL = [$STUDENT, $FACULTY, $ADMIN, $SUPERADMIN];
$NAVLINKS = $ALL[$SESSION->user_type - 1];

?>

<nav class="main-navbar" data-session-id="<?= $SESSION->user_id ?>" data-session-type="<?= $SESSION->user_type ?>">
    <div class="nav-body">
        <div class="nav-link-items">
            <?php foreach ($NAVLINKS as $link): ?>
                <?php if (!empty($link)): ?>
                    <?php
                    $match = $this->view_path === $link['path'] || '/' . $this->view_path === $link['path'];
                    ?>
                    <?php if (isset($link['sub-content'])): ?>

                        <?php
                        $link['sub-content'] = array_filter($link['sub-content'], function ($record) {
                            return count($record);
                        });

                        ?>
                        <a>
                        <?php else: ?>
                            <a href="<?= $link['path'] ?>">
                            <?php endif; ?>
                            <div class="nav-link <?= $match ? 'active' : '' ?>" data-path="<?= $link['path'] ?>">
                                <div class="main">
                                    <div class="icon">
                                        <?= $link['icon'] ?? '' ?>
                                    </div>
                                    <div class="text">
                                        <span>
                                            <?= $link['text'] ?>
                                        </span>
                                    </div>
                                </div>
                                <?php if (isset($link['sub-content'])): ?>
                                    <div class="sub-content" data-path="<?= $link['path'] ?>">
                                        <?php foreach ($link['sub-content'] as $item): ?>
                                            <?php
                                            $subMatch = $this->view_path === $item['path'] || '/' . $this->view_path === $item['path'];
                                            ?>
                                            <a href="<?= $item['path'] ?>">
                                                <div class="sub-link <?= $subMatch ? 'active' : '' ?>">
                                                    <div class="icon">
                                                        <?= $item['icon'] ?? '' ?>
                                                    </div>
                                                    <div class="text">
                                                        <span>
                                                            <?= $item['text'] ?>
                                                        </span>
                                                    </div>
                                                </div>
                                            </a>
                                        <?php endforeach; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
        </div>
    </div>
</nav>