<?php
global $APPLICATION,$SESSION;

$data = json_decode($_POST['data'], true);

$EVENT = $APPLICATION->FUNCTIONS->EVENT_CONTROL->get($data['id'], false);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Event</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Event Title</span>
                            </div>
                            <label for=""><span>Event Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Event Title" value="<?= $EVENT['title'] ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description</span>
                            </div>
                            <label for=""><span>Event Description</span></label>

                            <div class="error-container">
                                <div class="creator-textarea">
                                    <textarea name="description" id="editor" placeholder="What's on your mind, <?= $SESSION->displayName ?>">
                                        <?= $EVENT['description'] ?>
                                    </textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Date Start</span>
                            </div>
                            <label for=""><span>Date Start</span></label>

                            <div class="error-container">
                                <input type="datetime-local" name="date_start" placeholder="Date Start" value="<?= $EVENT['date_start'] ?>">
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Date End</span>
                            </div>
                            <label for=""><span>Date End</span></label>

                            <div class="error-container">
                                <input type="datetime-local" name="date_end" placeholder="Date End" value="<?= $EVENT['date_end'] ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>