<?php

global $APPLICATION, $CLASSROOMS_HEADER_BODY;

$control = $APPLICATION->FUNCTIONS->CLASSROOM_CONTROL;
$RECORDS = $control->getAllRecords(false);

?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Database Management</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>
</div>

<div class="right-content">

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Database Management</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>Reset Database</h2>
                                    </div>
                                </div>
                                <div class="center">
                                    
                                </div>
                                <div class="right"></div>
                            </div>
                            
                        </div>
                        <div class="main-table-body main-table-requests"  data-user-type="3">
                            <div class="reset-database-container" style="display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 10px;">
                            
                                <div class="reset-database-description">
                                    <p>This will reset the database to its initial state.</p>
                                </div>

                                <button class="btn btn-primary reset-database-button">Reset Database</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/superadmin/maintenance/database_management.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
