<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="icon" href="/public/assets/media/ui/logo.png" />
    <link rel="stylesheet" href="/public/assets/styles/css/styles.css">

</head>
<body>
    <div class="main-auth-container">
        <div class="auth-container">
            <div class="auth-left">
                <div class="background-image">
                    <img src="/public/assets/media/ui/logo-ui-2.png" alt="">
                </div>
            </div>
            <div class="auth-right">
                <form action="" class="form-control">
                    <div class="main-form">
                        <div class="main-header">
                            <h1>Welcome to 
                                <br>DYCI Brightpath!</h1>
                            <p class="">Please login to your Account</p>
                        </div>
                        <div class="main-content">
                            <div class="main-body">
                                <div class="form-group-container">
                                    <div class="form-group">
                                        <input type="email" placeholder="Email" name="email">
                                    </div>
                                </div>
                                <div class="form-group-container">
                                    <div class="form-group">
                                        <input type="password" placeholder="Password" name="password">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="link right">
                                        <a href="/forgot_password"><span>Forgot Password</span></a>
                                    </div>
                                </div>

                                <div class="form-group-container submit-group">
                                    <div class="form-group">
                                        <div class="submit-input" >
                                            <input type="submit" class="medium-width" value="SIGN IN">
                                        </div>
                                    </div>
                                </div>
                             
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <section id="big-pipes-container">
        <section id="system-messages"></section>
        <section id="system-notifications">
            <section id="system-notification"></section>
        </section>
        <section id="system-popup"></section>
    </section>
</body>
<script type="module" src="/public/assets/scripts/auth/login.js"> </script>
</html>