<?php
global $APPLICATION,$SESSION;

$data = json_decode($_POST['data'], true);

$courseControl = $APPLICATION->FUNCTIONS->COURSE_CONTROL;

$courses = $courseControl->getAllRecords(false);

$courses = ObjectToCombo("course_name", "course_id", $courses);

$record = $APPLICATION->FUNCTIONS->SUBJECT_CONTROL->get($data['id'], true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Subject</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject Name</span>
                            </div>
                            <label for=""><span>Subject Name</span></label>
                            <div class="error-container">
                                <input type="text" name="subject_name" placeholder="Subject Name" value="<?= $record->subject_name ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject Code</span>
                            </div>
                            <label for=""><span>Subject Code</span></label>
                            <div class="error-container">
                                <input type="text" name="subject_code" placeholder="Subject Name" value="<?= $record->subject_code ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Under Course</span>
                            </div>
                            <label for=""><span>Under Course</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("course_id", "Main Course", $courses, false, [
                                    "text" => $record->course->course_name,
                                    "value" => $record->course_id,
                                ]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>