<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$exam_id = $data['exam_id'];

$id = $data['id'];

$exam = $APPLICATION->FUNCTIONS->EXAM_CONTROL->get($exam_id, true);

$complied = $APPLICATION->FUNCTIONS->FORM_COMPLETION_CONTROL->get($id, true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Completed Form</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                     <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject</span>
                            </div>
                            <label for=""><span>Subject</span></label>
                            <div class="error-container">
                                <input type="text" name="subject" placeholder="Subject" value="<?= $exam->subject->subject_name ?>" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Title" value="<?= $exam->title ?>" readonly>
                            </div>
                        </div>
                    </div>


                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Duration</span>
                            </div>
                            <label for=""><span>Duration</span></label>

                            <div class="error-container">
                                <input type="text" name="duration" placeholder="Duration" value="<?= $exam->duration ?>" readonly>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Count Items</span>
                            </div>
                            <label for=""><span>Count Items</span></label>

                            <div class="error-container">
                                <input type="number" name="count_items" placeholder="Count Items" value="<?= $exam->count_items ?>" readonly>
                            </div>
                        </div>
                    </div>

                </div>

                <?php if($SESSION->user_type == 2): ?>
                    <div class="popup-footer">

                        <div class="form-group-container submit-group right-side flex">
                            <div class="form-group">
                                <div class="link view-btn" data-category="<?="Form" ?>" data-id="<?= $complied->form_completion_id ?>">
                                    <span>View Form</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <?php if ($complied->grade_score): ?>
                                    <div class="link edit-btn" data-category="<?="Form" ?>" data-id="<?= $complied->grade_score['grade_score_id'] ?>">
                                        <span>Edit Grade</span>
                                    </div>
                                <?php else: ?>
                                    <div class="link grade-btn" data-category="<?="Form" ?>" data-id="<?= $id ?>">
                                        <span>Grade Exam</span>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
              
            </form>
        </div>
    </div>
</div>