<?php

$data = json_decode($_POST['data'], true);

$email_address = $data['email_address'];
?>

<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Email Verification</h1>
                </div>
                <div class="paragraph">
                    <p>We have sent an email, through a registered email on your account. <b><?= $email_address ?></b></p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot auto-size">
                    
                   <div class="form-group-container">
                    <div class="form-group">
                        <label for="password">New Password</label>
                        <input type="password" name="password" id="password">
                    </div>
                   </div>

                   <div class="form-group-container">
                    <div class="form-group">
                        <label for="confirm-password">Confirm Password</label>
                        <input type="password" name="confirm-password" id="confirm-password">
                    </div>
                   </div>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Change">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>