<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Form</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" placeholder="Title" value="<?= $data['title'] ?>" readonly>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description</span>
                            </div>
                            <label for=""><span>Description</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" cols="30" rows="10"><?= $data['description'] ?></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Form Type</span>
                            </div>
                            <label for=""><span>Form Type</span></label>
                            <div class="error-container">
                                <?= CreateComboBox("form_type", "Form Type", [
                                    ["value" => "quiz", "text" => "Quiz"],
                                    ["value" => "survey", "text" => "Survey"],
                                    ["value" => "exam", "text" => "Exam"],
                                ]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Duration (Minutes)</span>
                            </div>
                            <label for=""><span>Duration (Minutes)</span></label>
                            <div class="error-container">
                                <input type="number" min="0" name="duration" placeholder="Duration (Minutes)" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Points</span>
                            </div>
                            <label for=""><span>Points</span></label>
                            <div class="error-container">
                                <input type="number" min="0" name="points" placeholder="Points" value="<?= $data['totalPoints'] ?>" readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>