<?php

global $APPLICATION, $SUBJECTS_IN_CLASSES_HEADER_BODY;

$d_data = json_decode($_POST['data'], true);
$data = $d_data['data'];
$section_id = $data['section_id'];

$control = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL;

$RECORDS = $control->filterRecords(["section_id" => $section_id], true);

// Fetch subjects for the professor
$RECORDS = array_map(fn($record) => (object) [
    'subject_name' => $record->subject->subject_name,
    'classroom_id' => $record->classroom ? $record->classroom->classroom_name : "",
    'section_subject_id' => $record->section_subject_id,
    'mon' => $record->mon ? $record->mon : "",
    'tue' => $record->tue ? $record->tue : "",
    'wed' => $record->wed ? $record->wed : "",
    'thu' => $record->thu ? $record->thu : "",
    'fri' => $record->fri ? $record->fri : "",
    'sat' => $record->sat ? $record->sat : "",
], $RECORDS);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table go-large">
            <div class="popup-top">
                <div class="headline">
                    <h1>Select Subject</h1>
                </div>
                <div class="paragraph">
                    <p>You can select multiple subjects.</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="data-table-content ">
                        <div class="main-table-container table-component full">
                            <div class="main-table-header">
                                <div class="table-header">
                                    <div class="left">
                                        <div class="title">
                                            <h2>Select Subjects</h2>
                                        </div>
                                    </div>
                                    <div class="center">
                                        <div class="search-engine-parent full-width">
                                            <div class="search-engine">
                                                <div class="icon">
                                                    <?= UseIcon("magnifying-glass-thin") ?>
                                                </div>
                                                <input type="text" name="search-records" placeholder="Search Records...">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="right"></div>
                                </div>
                                <div class="table-buttons">
                                    <div class="left"></div>
                                    <div class="right">
                                        <div class="icon-button table-button show-component" data-name="select-request">
                                            <div class="icon">
                                                <?= UseIcon("eye-thin") ?>
                                            </div>
                                            <div class="text">
                                                <span>Select Subject</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="main-table-body main-table-requests">
                                    <?= CreateTable([
                                        "content" => $SUBJECTS_IN_CLASSES_HEADER_BODY,
                                        "data" => $RECORDS,
                                        "id" => "section_subject_id"
                                    ]) ?>
                                </div>
                            </div>
                        </div>
                    </div>

            </form>
        </div>
    </div>
</div>