<?php
global $APPLICATION, $SUBJECTS_IN_CLASSES_HEADER_BODY;


$data = json_decode($_POST['data'], true);
$id = $data['section_student_id'];

$control = $APPLICATION->FUNCTIONS->SECTION_STUDENT_IRREGULAR_SUBJECT_CONTROL;
// $userControl = $APPLICATION->FUNCTIONS->USER_CONTROL;
// $courseControl = $APPLICATION->FUNCTIONS->COURSE_CONTROL;
// $sectionStudentControl = $APPLICATION->FUNCTIONS->SECTION_STUDENT_CONTROL;
// $sectionSubjectControl = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL;

// $section = $control->get($id, true);
// $students = $sectionStudentControl->filterRecords(['section_id' => $id, 'irregular' => 'irregular'], true);
// $subjects = $sectionSubjectControl->filterRecords(['section_id' => $id], true);

$records = $control->filterRecords(['section_student_id' => $id], true);

$records = array_map(fn($record) => (object) [
    'id' => $record->irregular_subject_id,
    'subject_name' => $record->section_subject->subject->subject_name,
    'classroom_id' => $record->section_subject->classroom ? $record->section_subject->classroom->classroom_name : "",
    'section_subject_id' => $record->section_subject_id,
    'mon' => $record->section_subject->mon ? $record->section_subject->mon : "",
    'tue' => $record->section_subject->tue ? $record->section_subject->tue : "",
    'wed' => $record->section_subject->wed ? $record->section_subject->wed : "",
    'thu' => $record->section_subject->thu ? $record->section_subject->thu : "",
    'fri' => $record->section_subject->fri ? $record->section_subject->fri : "",
    'sat' => $record->section_subject->sat ? $record->section_subject->sat : "",
], $records);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Student Subjects</h1>
                </div>
                <div class="paragraph">
                    <p>List of students</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                  
                <div class="data-table-content">
                    <div class="main-table-container table-component full">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>Student Subjects</h2>
                                    </div>
                                </div>
                                <div class="center"></div>
                                <div class="right"></div>
                            </div>
                            <div class="table-buttons">
                                <div class="left"></div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests">
                            <?= CreateTable([
                                "content" => $SUBJECTS_IN_CLASSES_HEADER_BODY,
                                "data" => $records,
                                "id" => "id"
                            ]) ?>
                        </div>
                    </div>
                </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>