<?php
global $APPLICATION, $STUDENT_IN_SECTION_HEADER_BODY, $SECTION_SUBJECT_HEADER_BODY;


$data = json_decode($_POST['data'], true);
$id = $data['section_id'];

$control = $APPLICATION->FUNCTIONS->SECTION_CONTROL;
$userControl = $APPLICATION->FUNCTIONS->USER_CONTROL;
$courseControl = $APPLICATION->FUNCTIONS->COURSE_CONTROL;
$sectionStudentControl = $APPLICATION->FUNCTIONS->SECTION_STUDENT_CONTROL;
$sectionSubjectControl = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL;

$section = $control->get($id, true);
$students = $sectionStudentControl->filterRecords(['section_id' => $id, 'irregular' => 'irregular'], true);
$subjects = $sectionSubjectControl->filterRecords(['section_id' => $id], true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Section</h1>
                </div>
                <div class="paragraph">
                    <p>List of students</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                  
                <div class="data-table-content">
                    <div class="main-table-container table-component full">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>Irregular Students</h2>
                                    </div>
                                </div>
                                <div class="center"></div>
                                <div class="right"></div>
                            </div>
                            <div class="table-buttons">
                                <div class="left"></div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests">
                            <?= CreateTable([
                                "content" => $STUDENT_IN_SECTION_HEADER_BODY,
                                "data" => $students,
                                "id" => "section_student_id"
                            ]) ?>
                        </div>
                    </div>
                </div>


                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>